version: '3'
services:
  front-end:
    container_name: react-app
        Dockerfile : ./client_src/Dockerfile
        build : .
        ports :
          - "3000:3000"
        volumes:
          ../front
  back-end:
    container_name: loopback-app
    build : .
    ports :
          - "5000:5000"
        volumes:
          ../backend

